export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';

export const UPDADE_STATUS_ASSGNMENT = 'UPDADE_STATUS_ASSGNMENT';

export const UPDADE_ASSGNMENT_TITLE = 'UPDADE_ASSGNMENT_TITLE';

export const DELETE_ASSGNMENT = 'DELETE_ASSGNMENT';
